import * as path from "path";
import * as fs from "fs";
import { parseArgs, readString } from "../lib/args.js";
import { exists, readText, resolvePath, writeText } from "../lib/files.js";
import { fail } from "../lib/errors.js";

function readConfig(project: string): Record<string, string> {
  const config = path.join(project, "99_meta", "scaffold_decisions.md");
  const values: Record<string, string> = {
    project_id: path.basename(project),
    linking_mode: "plain",
  };
  if (!exists(config)) {
    return values;
  }

  let inBlock = false;
  for (const line of readText(config).split(/\r?\n/)) {
    if (line.trim() === "```yaml") {
      inBlock = true;
      continue;
    }
    if (inBlock && line.trim() === "```") {
      break;
    }
    if (inBlock && line.includes(":")) {
      const separator = line.indexOf(":");
      values[line.slice(0, separator).trim()] = line
        .slice(separator + 1)
        .trim()
        .replace(/^"|"$/g, "");
    }
  }
  return values;
}

function parseFrontmatter(filePath: string): Record<string, string> {
  const text = readText(filePath);
  if (!text.startsWith("---")) {
    return {};
  }
  const parts = text.split("---", 3);
  if (parts.length < 3) {
    return {};
  }
  const data: Record<string, string> = {};
  for (const line of parts[1].split(/\r?\n/)) {
    if (line.includes(":") && !line.startsWith(" ")) {
      const separator = line.indexOf(":");
      data[line.slice(0, separator).trim()] = line
        .slice(separator + 1)
        .trim()
        .replace(/^"|"$/g, "");
    }
  }
  return data;
}

function titleFromFile(filePath: string, meta: Record<string, string>): string {
  if (meta.topic) {
    return meta.topic;
  }
  const stem = path.basename(filePath, path.extname(filePath)).replace(/^\d{4}-\d{2}-\d{2}_/, "");
  return stem.replace(/_/g, " ");
}

function linkFor(project: string, filePath: string, label: string, mode: string): string {
  const rel = path.relative(project, filePath).split(path.sep).join("/");
  if (mode === "obsidian") {
    return rel.endsWith(".md") ? `[[${rel.slice(0, -3)}|${label}]]` : `[[${rel}|${label}]]`;
  }
  return rel.startsWith("04_discussions/") ? `[${label}](../${rel})` : `[${label}](${rel})`;
}

export function updateIndexCommand(argv: string[], cwd = process.cwd()): number {
  const args = parseArgs(argv);
  const project = resolvePath(readString(args, "project") ?? ".", cwd);
  const discussions = path.join(project, "04_discussions");
  if (!exists(discussions)) {
    fail(`Missing discussion folder: ${discussions}`);
  }

  const config = readConfig(project);
  const mode = config.linking_mode ?? "plain";
  const entries: Array<{ date: string; title: string; status: string; filePath: string }> = [];
  const files = fs.readdirSync(discussions) as string[];
  for (const name of files.sort()) {
    const filePath = path.join(discussions, name);
    if (name.startsWith("_") || !name.endsWith(".md") || !fs.statSync(filePath).isFile()) {
      continue;
    }
    const meta = parseFrontmatter(filePath);
    entries.push({
      date: meta.date ?? "unknown-date",
      title: titleFromFile(filePath, meta),
      status: meta.status ?? "unknown",
      filePath,
    });
  }

  const lines = [
    "---",
    "type: discussion_index",
    `project: ${config.project_id ?? path.basename(project)}`,
    "status: active",
    "---",
    "",
    "# Discussion Index",
    "",
    "This file is generated by `rds update-index`.",
    "",
    "## Recent Discussions",
    "",
  ];

  if (entries.length > 0) {
    for (const entry of entries.sort((left, right) =>
      `${right.date}\u0000${right.title}`.localeCompare(`${left.date}\u0000${left.title}`),
    )) {
      lines.push(
        `- ${entry.date} - ${linkFor(project, entry.filePath, entry.title, mode)} (${entry.status})`,
      );
    }
  } else {
    lines.push("_No discussions recorded yet._");
  }
  lines.push("", "## By Topic", "", "_Add topic groupings as discussions accumulate._", "");

  const indexPath = path.join(discussions, "_index.md");
  writeText(indexPath, lines.join("\n"));
  console.log(`Updated ${indexPath}`);
  return 0;
}
