import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { fileURLToPath } from "url";
import { describe, test, expect } from "vitest";
import { scaffoldCommand } from "../commands/scaffold.js";
import { convertLinkingCommand } from "../commands/convert-linking.js";
import { updateIndexCommand } from "../commands/update-index.js";
import { PROJECT_REQUIRED, runValidation } from "../commands/validate.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

function withTempProject(fn: (dir: string, project: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "rds-test-"));
  const project = path.join(dir, "project");
  try {
    fn(dir, project);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

describe("rds commands", () => {
  test("scaffold creates a valid RDS project", () => {
    withTempProject((_dir, project) => {
      const status = scaffoldCommand(
        [
          "--target",
          project,
          "--project-id",
          "test_project",
          "--field",
          "biology",
          "--topic",
          "Cartilage repair",
          "--scaffold",
          "wet_lab",
          "--linking-mode",
          "plain",
          "--with-glossary",
        ],
        repoRoot,
      );
      expect(status).toBe(0);
      expect(runValidation("Project", project, PROJECT_REQUIRED, false)).toBe(0);
      expect(fs.existsSync(path.join(project, "AGENTS.md"))).toBe(true);
      expect(fs.existsSync(path.join(project, "00_context", "glossary.md"))).toBe(true);

      const overview = path.join(project, "00_context", "project_overview.md");
      fs.writeFileSync(overview, "keep existing context\n", "utf8");
      expect(
        scaffoldCommand(
          [
            "--target",
            project,
            "--field",
            "biology",
            "--topic",
            "Cartilage repair",
            "--scaffold",
            "wet_lab",
            "--force",
          ],
          repoRoot,
        ),
      ).toBe(0);
      expect(fs.readFileSync(overview, "utf8")).toBe("keep existing context\n");
    });
  });

  test("convert-linking rewrites Markdown links and runtime config", () => {
    withTempProject((_dir, project) => {
      scaffoldCommand(
        [
          "--target",
          project,
          "--field",
          "biology",
          "--topic",
          "Cartilage repair",
          "--scaffold",
          "wet_lab",
        ],
        repoRoot,
      );
      const overview = path.join(project, "00_context", "project_overview.md");
      fs.appendFileSync(overview, "\nSee [Index](../04_discussions/_index.md).\n", "utf8");
      const discussion = path.join(project, "04_discussions", "2026-04-17_cartilage.md");
      fs.writeFileSync(
        discussion,
        [
          "---",
          "date: 2026-04-17",
          "topic: Cartilage plan",
          "status: active",
          "---",
          "",
          "# Cartilage plan",
          "",
        ].join("\n"),
        "utf8",
      );
      expect(updateIndexCommand(["--project", project])).toBe(0);

      expect(convertLinkingCommand(["--target", project, "--to", "obsidian"])).toBe(0);
      expect(fs.readFileSync(overview, "utf8")).toContain("[[04_discussions/_index|Index]]");
      expect(fs.readFileSync(path.join(project, "04_discussions", "_index.md"), "utf8")).toContain(
        "[[04_discussions/2026-04-17_cartilage|Cartilage plan]]",
      );
      expect(
        fs.readFileSync(path.join(project, "99_meta", "scaffold_decisions.md"), "utf8"),
      ).toContain('linking_mode: "obsidian"');
      expect(runValidation("Project", project, PROJECT_REQUIRED, true)).toBe(0);
    });
  });

  test("update-index lists discussion files", () => {
    withTempProject((_dir, project) => {
      scaffoldCommand(
        [
          "--target",
          project,
          "--field",
          "biology",
          "--topic",
          "Cartilage repair",
          "--scaffold",
          "wet_lab",
        ],
        repoRoot,
      );
      const discussion = path.join(project, "04_discussions", "2026-04-17_cartilage.md");
      fs.writeFileSync(
        discussion,
        [
          "---",
          "date: 2026-04-17",
          "topic: Cartilage plan",
          "status: active",
          "---",
          "",
          "# Cartilage plan",
          "",
        ].join("\n"),
        "utf8",
      );

      expect(updateIndexCommand(["--project", project])).toBe(0);
      const index = fs.readFileSync(path.join(project, "04_discussions", "_index.md"), "utf8");
      expect(index).toContain("Cartilage plan");
      expect(index).toContain("This file is generated by `rds update-index`.");
    });
  });
});
